# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazychez < Formula
  desc "A terminal UI for managing chezmoi dotfiles with integrated git operations"
  homepage "https://github.com/nickrotondo/lazychez"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nickrotondo/lazychez/releases/download/v0.5.0/lazychez_darwin_amd64.tar.gz"
      sha256 "9c2f0d9cf53bba183171f20aa25207822b01dbf202a3ca6df8cc096b0ca01adf"

      define_method(:install) do
        bin.install "lazychez"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nickrotondo/lazychez/releases/download/v0.5.0/lazychez_darwin_arm64.tar.gz"
      sha256 "44c1370a034c7011f79ded230e6b1729a75deb4c4c6a88d93dfc5543ec97add9"

      define_method(:install) do
        bin.install "lazychez"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nickrotondo/lazychez/releases/download/v0.5.0/lazychez_linux_amd64.tar.gz"
      sha256 "acaff8c5fe00d6407d66869bd22faaa7301be1591ea0a9c934543f485d13d663"
      define_method(:install) do
        bin.install "lazychez"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nickrotondo/lazychez/releases/download/v0.5.0/lazychez_linux_arm64.tar.gz"
      sha256 "0ae08618c6d2620e007dd20cd292601637f7fafed8fbf81c1477aa5b50457237"
      define_method(:install) do
        bin.install "lazychez"
      end
    end
  end
end
