# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazychez" do
  name "lazychez"
  desc "A terminal UI for managing chezmoi dotfiles with integrated git operations"
  homepage "https://github.com/nickrotondo/lazychez"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazychez"

  on_macos do
    on_intel do
      url "https://github.com/nickrotondo/lazychez/releases/download/v#{version}/lazychez_darwin_amd64.tar.gz"
      sha256 "b6e3cb3a6b4aa9a90b7b6baa386192e7979b1ae9db45a02eb5ec8bfde77a3052"
    end
    on_arm do
      url "https://github.com/nickrotondo/lazychez/releases/download/v#{version}/lazychez_darwin_arm64.tar.gz"
      sha256 "95ec8ce9d00d3945a5f35686d0467c9792e32ea322b13bb8ca9a922050e64133"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nickrotondo/lazychez/releases/download/v#{version}/lazychez_linux_amd64.tar.gz"
      sha256 "079e940a6c6168eeaa22c254451d9a46719464bc077309c41ad19ecad0431797"
    end
    on_arm do
      url "https://github.com/nickrotondo/lazychez/releases/download/v#{version}/lazychez_linux_arm64.tar.gz"
      sha256 "eee99f06183bb6655159021f08c4662ffbf57f1c8a6901f399f928f4a23c5e42"
    end
  end

  # No zap stanza required
end
