# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazychez" do
  name "lazychez"
  desc "A terminal UI for managing chezmoi dotfiles with integrated git operations"
  homepage "https://github.com/nickrotondo/lazychez"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazychez"

  on_macos do
    on_intel do
      url "https://github.com/nickrotondo/lazychez/releases/download/v#{version}/lazychez_darwin_amd64.tar.gz"
      sha256 "72d12099a5533b50466d29c4ea1be978df4e772ad44e8efd22b06b9781db3d41"
    end
    on_arm do
      url "https://github.com/nickrotondo/lazychez/releases/download/v#{version}/lazychez_darwin_arm64.tar.gz"
      sha256 "9d49a7e84bbaaef2a41f804c1b2af5e4059d85f3d565dbce58c263f135fcd5e5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nickrotondo/lazychez/releases/download/v#{version}/lazychez_linux_amd64.tar.gz"
      sha256 "3ff929e33fb531b2394818e9fc7c665c1e269f00b4153a130ec238eecd21a1a3"
    end
    on_arm do
      url "https://github.com/nickrotondo/lazychez/releases/download/v#{version}/lazychez_linux_arm64.tar.gz"
      sha256 "f7553eb4c77bd0377170d3139843441c5743b5d2bf9a023df181084a26bcb18a"
    end
  end

  # No zap stanza required
end
