# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazychez" do
  name "lazychez"
  desc "A terminal UI for managing chezmoi dotfiles with integrated git operations"
  homepage "https://github.com/nickrotondo/lazychez"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazychez"

  on_macos do
    on_intel do
      url "https://github.com/nickrotondo/lazychez/releases/download/v#{version}/lazychez_darwin_amd64.tar.gz"
      sha256 "88770f7a674f65924adc79cd353b79cc8673682365e9d9059095a10492e64a91"
    end
    on_arm do
      url "https://github.com/nickrotondo/lazychez/releases/download/v#{version}/lazychez_darwin_arm64.tar.gz"
      sha256 "fd9dbb0518e221969afd3cd8fbdf64f06f667f8836fc9c513be5b6a191689cd5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nickrotondo/lazychez/releases/download/v#{version}/lazychez_linux_amd64.tar.gz"
      sha256 "0809a42a0116dcd7233900046dce6a895254b109be52e279bbbfc258e4b27af0"
    end
    on_arm do
      url "https://github.com/nickrotondo/lazychez/releases/download/v#{version}/lazychez_linux_arm64.tar.gz"
      sha256 "4b8d17b42ae1aa3241691f51ea844f2595fd0f7220e834ba19113509a319c5a5"
    end
  end

  # No zap stanza required
end
